### ISSUE TITLE
권한 설정, 코드리뷰

### ISSUE THREAD

**Issue by joy2256** [teenting/Backend#31]

**Comment by yunzzoii** [comment]
mission, achievement 조회(get)시 현재 로그인된 유저의 자녀만 접근할 수 있도록 변경

**Comment by yunzzoii** [comment]
mission update시 에러... ㅠㅠ

**Comment by yunzzoii** [comment]
mission update시 에러 수정 완료. 
custom한 get_qureyset을 request가 get일때만 사용하게 함.
